### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by stepanenko3** [outl1ne/nova-translatable#73]
Hi,

Please add support for Nova 4

**Comment by nicoeg** [comment]
I've created a fork with some fixes for Nova 4. It might not work in all cases but worked during my testing. 
I had to update some styling but tried to keep it pretty close to the current version.
The libraries are a little bit bigger because I have to pull in some deps that the `packages.js` file (laravel-nova replacement) uses in order for it to work. I'm not sure if there is a better way of doing it.

You can use it by pointing the composer library to my fork and using the `feature/nova-4` branch as the version.
```json
"optimistdigital/nova-translatable": "dev-feature/nova-4",
```

```json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/nicoeg/nova-translatable"
    }
],
```

More info on how to use a Github branch in composer: https://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency

**Comment by stepanenko3** [comment]
@nicoeg, does not working with Nova 4 Slug fields

**Comment by stepanenko3** [comment]
@nicoeg, Are you planning to make a pull request?

**Comment by nicoeg** [comment]
@stepanenko3 
> And a visual bug. Need to add padding

The `pt-4` class has been removed by Nova which is why it was missing padding. I changed it to use the `pt-3` class now.

> does not working with Nova 4 Slug fields

I'm not using the slug field so I haven't tested with that but feel free to create a PR with a fix if you find one.

> Are you planning to make a pull request?  

I was originally but since this is not backward compatible they'll have to maintain a separate branch for Nova 4. So I think it's better for them to decide which direction they want to take.

**Comment by stepanenko3** [comment]
@nicoeg 
I found 1 more bug
If I change the lang in the Code field, the content is not displayed until I click on the code area
![](https://i.snipboard.io/ZWvo0S.jpg)

**Comment by stepanenko3** [comment]
@nicoeg 
> The libraries are a little bit bigger because I have to pull in some deps that the packages.js file (laravel-nova replacement) uses in order for it to work. I'm not sure if there is a better way of doing it.

In web pack.mix.js

  .alias({
    'laravel-nova': path.join(__dirname, 'vendor/laravel/nova/resources/js/mixins/packages.js'),
  })

**Comment by nicoeg** [comment]
It also contains this in the `nova-extension.js` file :)

**Comment by scramatte** [comment]
+1

**Comment by billyjustal** [comment]
+1
